### ISSUE TITLE
App crash after implementation 'com.google.ads.mediation:facebook:6.3.0.1' 

### ISSUE THREAD

**Issue by ahmadeyamin** [BetOnYou/react-native-mediation-test-suite#1]
Thank you so much for developing this package.

My problem is your package is working fine with Admob. But it crashes when I add "audience-network-sdk:6.3.0".

Crash here
```
    implementation 'com.google.android.gms:play-services-ads:19.8.0'
    implementation 'com.facebook.android:audience-network-sdk:6.3.0'
    implementation 'com.google.ads.mediation:facebook:6.3.0.1'
```
Crash here
```
    implementation 'com.google.android.gms:play-services-ads:19.8.0'
    implementation 'com.google.ads.mediation:facebook:6.3.0.1'
```

Work here
```
    implementation 'com.google.android.gms:play-services-ads:19.8.0'
    implementation 'com.facebook.android:audience-network-sdk:6.3.0'
```

It crash if I add "com.google.ads.mediation:facebook:6.3.0.1" this

![image](https://user-images.githubusercontent.com/29674341/115124148-923f9d80-9fe2-11eb-8125-cd8d44a6de07.png)

It will be good if you can help :)

**Comment by zyzo** [comment]
Hi @ahmadeyamin, what is the native error log for this crash in Android Studio ? Maybe that info will help to find the solution.

**Comment by ahmadeyamin** [comment]
![image](https://user-images.githubusercontent.com/29674341/115152268-41877d80-a092-11eb-80d8-6a306a7d7ee4.png)

**Comment by zyzo** [comment]
Thanks for your response. Could you try to call `MobileAds.initialize` in your MainActivity, as shown [here](https://developers.google.com/admob/android/quick-start), to see if it fixes your problem ? 

```java
package ...
import ...
import com.google.android.gms.ads.MobileAds;
import com.google.android.gms.ads.initialization.InitializationStatus;
import com.google.android.gms.ads.initialization.OnInitializationCompleteListener;

public class MainActivity extends AppCompatActivity {

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MobileAds.initialize(this, new OnInitializationCompleteListener() {
            @Override
            public void onInitializationComplete(InitializationStatus initializationStatus) {
            }
        });
    }
}
```

**Comment by ahmadeyamin** [comment]
Thank You so much 

```
 setContentView(R.layout.activity_main);
```

It's working after removing this line :)
